//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutcomeQueryView
    {
        public double number { get; set; }
        public string unit { get; set; }
        public System.DateTime recipientsTime { get; set; }
        public Nullable<double> price { get; set; }
        public string instructions { get; set; }
        public Nullable<double> unitPrice { get; set; }
        public string code { get; set; }
        public string materialName { get; set; }
        public string modelName { get; set; }
        public string categoryName { get; set; }
        public string name { get; set; }
        public int OutId { get; set; }
        public int mfId { get; set; }
        public string manufacturersName { get; set; }
        public int codeId { get; set; }
        public int deparId { get; set; }
        public string departmentName { get; set; }
        public int emploId { get; set; }
        public string projectName { get; set; }
        public string positionName { get; set; }
        public Nullable<int> state { get; set; }
        public string priceMeasure { get; set; }
        public string brandCodeName { get; set; }
    }
}
