//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using DbInterface;
    using System;
    using System.Collections.Generic;
    
    public partial class QualityCertificationReportImg
    {
        public int id { get; set; }
        public int incomeId { get; set; }
        public byte[] img { get; set; }

        public static QualityCertificationReportImg Insert(int incomeId, byte[] imgBytes, IDbInterface dbInterface)
        {
            QualityCertificationReportImg img = new QualityCertificationReportImg() { incomeId = incomeId, img = imgBytes };
            dbInterface.Insert(img, false);
            return img;
        }
    }
}
